import foolinks from '../data/foolinks.json';
export const shopPagePathToProduct = '/shop/product/:id';
export const shopPagePathToCategory = '/shop/:categoryId';
export const landingPagePath = '/';
export const productOverviewPagePath = '/product/:id';
export const aboutUsPath = foolinks[0].links[0].url;
export const privacyPolicyPath = foolinks[0].links[1].url;
export const termsAndCondPath = foolinks[0].links[2].url;
export const loginPath = "/login";
export const registrationPath = "/register";
